"""Tests for tag write-back op generation (the safe, pure part of tagger.py).

The safety-critical invariant: CostDNA must never emit a tag-write for a
low-confidence prediction. That's the entire reason the confidence column
exists. These tests pin that behavior plus per-resource-type command
correctness. (The live boto3 path, apply_tags_live, isn't unit-tested here —
it requires real AWS — but every op it would execute is generated by
build_tag_ops, which is fully covered.)
"""

from __future__ import annotations

import pandas as pd

from costdna.tagger import build_tag_ops


def _df(rows):
    return pd.DataFrame(rows)


def test_low_confidence_predictions_are_never_tagged():
    df = _df([
        {"resource_id": "i-high", "resource_type": "ec2", "team_pred": "ml", "confidence": 0.95},
        {"resource_id": "i-low",  "resource_type": "ec2", "team_pred": "ml", "confidence": 0.40},
        {"resource_id": "i-edge", "resource_type": "ec2", "team_pred": "data", "confidence": 0.70},
    ])
    ops = build_tag_ops(df)                      # default threshold 0.7
    ids = {op.resource_id for op in ops}
    assert "i-high" in ids                       # 0.95 ≥ 0.7 → tagged
    assert "i-edge" in ids                       # 0.70 ≥ 0.7 → tagged (boundary inclusive)
    assert "i-low" not in ids                    # 0.40 < 0.7 → NEVER tagged


def test_custom_threshold_respected():
    df = _df([
        {"resource_id": "r1", "resource_type": "ec2", "team_pred": "ml", "confidence": 0.85},
        {"resource_id": "r2", "resource_type": "ec2", "team_pred": "ml", "confidence": 0.80},
    ])
    ops = build_tag_ops(df, min_confidence=0.82)
    ids = {op.resource_id for op in ops}
    assert ids == {"r1"}, "only predictions ≥ custom threshold should be tagged"


def test_command_per_resource_type_and_inferred_marker():
    df = _df([
        {"resource_id": "i-abc", "resource_type": "ec2", "team_pred": "ml", "confidence": 0.9},
        {"resource_id": "db-1",  "resource_type": "rds", "team_pred": "data", "confidence": 0.9},
        {"resource_id": "fn-1",  "resource_type": "lambda", "team_pred": "backend", "confidence": 0.9},
        {"resource_id": "buk-1", "resource_type": "s3", "team_pred": "platform", "confidence": 0.9},
    ])
    ops = {op.resource_id: op.cli_command for op in build_tag_ops(df)}
    assert ops["i-abc"].startswith("aws ec2 create-tags")
    assert "rds add-tags-to-resource" in ops["db-1"]
    assert "lambda tag-resource" in ops["fn-1"]
    assert "s3api put-bucket-tagging" in ops["buk-1"]
    # Every write must carry the provenance marker so a later run / human can
    # tell which tags CostDNA wrote.
    for cmd in ops.values():
        assert "costdna:inferred" in cmd, f"missing provenance marker: {cmd}"
        assert "true" in cmd


def test_team_value_is_shell_quoted():
    df = _df([
        {"resource_id": "i-x", "resource_type": "ec2",
         "team_pred": "team with spaces", "confidence": 0.9},
    ])
    op = build_tag_ops(df)[0]
    # shlex.quote should wrap the value so the CLI command is safe to paste.
    assert "'team with spaces'" in op.cli_command


def test_empty_predictions_returns_no_ops():
    df = _df([
        {"resource_id": "r1", "resource_type": "ec2", "team_pred": "ml", "confidence": 0.1},
    ])
    assert build_tag_ops(df) == []
